micronaut:
  application:
    name: keymanagerRest

#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/rest
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: root
#    schema-generate: CREATE_DROP
#jpa.default.properties.hibernate.hbm2ddl.auto: update

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      addres: http://localhost:50051

jackson:
  serialization:
  writeDateAsTimestamps: false
